package com.cerner.oauth2.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class Oauth2Controller {

	// no tokens needed; can be accessed by any authorized user with any role
	@GetMapping(path = "/public")
	public String publicPage() {
		return "Public Page";
	}

	// oauth token generated by authorized user with role "USER"
	@GetMapping(path = "/private")
	public String privatePage() {
		return "Private Page";
	}

	// oauth token generated by authorized user with role "USER"
	@GetMapping(path = "/private/param")
	public String privatePage(@RequestParam(name = "privateParam", required = true) String param) {
		return "Private Page" + param;
	}

	// oauth token generated by authorized user with role "ADMIN"
	@GetMapping(path = "/admin")
	public String adminPage() {
		return "Administrator Page";
	}

	// oauth token generated by authorized user with role "ADMIN"
	@PostMapping(path = "/admin")
	public String adminPage(@RequestBody(required = true) String param) {
		return "Administrator Page" + param;
	}

}
